//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHECD.EntityFramework.EFWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EHECD_UnitUser
    {
        public long ID { get; set; }
        public string sLoginName { get; set; }
        public string sPassWord { get; set; }
        public string sRealName { get; set; }
        public long iUnitRoleID { get; set; }
        public int iUserType { get; set; }
        public int iUserUnitType { get; set; }
        public int iUnitID { get; set; }
        public bool iStatus { get; set; }
        public System.DateTime dCreateTime { get; set; }
        public bool bIsDeleted { get; set; }
    }
}
