//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHECD.EntityFramework.EFWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EHECD_PhoneMsg
    {
        public long ID { get; set; }
        public string sPhone { get; set; }
        public string sCode { get; set; }
        public System.DateTime dSendTime { get; set; }
        public System.DateTime dValidTime { get; set; }
        public int iType { get; set; }
        public int iState { get; set; }
    }
}
