//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHECD.EntityFramework.EFWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EHECD_ActionLog
    {
        public long ID { get; set; }
        public long iUserID { get; set; }
        public string sType { get; set; }
        public string sIpAddress { get; set; }
        public string sContent { get; set; }
        public System.DateTime dInsertTime { get; set; }
    }
}
