//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHECD.EntityFramework.EFWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EHECD_UnitModule
    {
        public long ID { get; set; }
        public long iPID { get; set; }
        public string sModuleName { get; set; }
        public string sModuleUrl { get; set; }
        public int iOrderID { get; set; }
        public bool bIsDeleted { get; set; }
        public System.DateTime dInsertTime { get; set; }
        public int RoleType { get; set; }
        public int iUnitType { get; set; }
        public bool bIsLink { get; set; }
    }
}
