//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHECD.EntityFramework.EFWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EHECD_ActionLog> EHECD_ActionLog { get; set; }
        public virtual DbSet<EHECD_Module> EHECD_Module { get; set; }
        public virtual DbSet<EHECD_ModuleAction> EHECD_ModuleAction { get; set; }
        public virtual DbSet<EHECD_PhoneMsg> EHECD_PhoneMsg { get; set; }
        public virtual DbSet<EHECD_Role> EHECD_Role { get; set; }
        public virtual DbSet<EHECD_RoleAction> EHECD_RoleAction { get; set; }
        public virtual DbSet<EHECD_UnitActionLog> EHECD_UnitActionLog { get; set; }
        public virtual DbSet<EHECD_UnitModule> EHECD_UnitModule { get; set; }
        public virtual DbSet<EHECD_UnitModuleAction> EHECD_UnitModuleAction { get; set; }
        public virtual DbSet<EHECD_UnitRole> EHECD_UnitRole { get; set; }
        public virtual DbSet<EHECD_UnitRoleAction> EHECD_UnitRoleAction { get; set; }
        public virtual DbSet<EHECD_UnitUser> EHECD_UnitUser { get; set; }
        public virtual DbSet<EHECD_User> EHECD_User { get; set; }
    }
}
